language: elixir
sudo:     false


jobs:
  include:
    - &test
      stage:          test
      elixir:         1.2.6
      otp_release:    18.0
      env:            MIX_ENV=test TRAVIS_COVERAGE=true
      before_install: . ${TRAVIS_BUILD_DIR}/travis/ex_unit_before_install.sh
      script:         . ${TRAVIS_BUILD_DIR}/travis/ex_unit_script.sh
      after_success:  . ${TRAVIS_BUILD_DIR}/travis/ex_unit_after_success.sh
    - <<: *test
      elixir:         1.3.4
      otp_release:    18.0
      env:            MIX_ENV=test
    - <<: *test
      elixir:         1.4.2
      otp_release:    18.0
      env:            MIX_ENV=test
    - <<: *test
      elixir:         1.4.2
      otp_release:    19.0
      env:            MIX_ENV=test
    - stage:          verify
      elixir:         1.2.6
      otp_release:    18.0
      before_install: . ${TRAVIS_BUILD_DIR}/travis/verify_before_install.sh
      script:         . ${TRAVIS_BUILD_DIR}/travis/verify_script.sh
      after_success:  . ${TRAVIS_BUILD_DIR}/travis/verify_after_success.sh
