language:    erlang
otp_release: 17.0

sudo: false
env:
  - TEST_ENV=ex_unit
  - TEST_ENV=verify

before_install: . ./travis/${TEST_ENV}_before_install.sh
install:        . ./travis/${TEST_ENV}_install.sh
script:         . ./travis/${TEST_ENV}_script.sh
after_success:  . ./travis/${TEST_ENV}_after_success.sh
