language:    elixir
otp_release: 18.0
elixir:      1.2.6
sudo:        false

env:
  - MIX_ENV=test TEST_ENV=ex_unit TRAVIS_COVERAGE=true
  - MIX_ENV=prod TEST_ENV=verify

matrix:
  include:
    - elixir: 1.3.4
      env:    MIX_ENV=test TEST_ENV=ex_unit
    - elixir: 1.4.2
      env:    MIX_ENV=test TEST_ENV=ex_unit
    - elixir:      1.4.2
      otp_release: 19.0
      env:         MIX_ENV=test TEST_ENV=ex_unit

before_install: . ${TRAVIS_BUILD_DIR}/travis/${TEST_ENV}_before_install.sh
script:         . ${TRAVIS_BUILD_DIR}/travis/${TEST_ENV}_script.sh
after_success:  . ${TRAVIS_BUILD_DIR}/travis/${TEST_ENV}_after_success.sh
